name: Release Gem to rubygems.org

on:
  push:
    tags:
      - v*

jobs:
  push:
    if: github.repository == 'globalize/globalize'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      # Set up
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby

      # Release
      - uses: rubygems/release-gem@v1
